---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodeapp-pipeline
  namespace: rdapp
spec:
  params:
    - name: REPO
      type: string
    - name: IMAGE_REF
      type: string
    - name: IMAGE_TAG
      type: string
  workspaces:
    - name: linked-workspace
    - name: git-basic-auth
    - name: config-dir
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: basic-auth
          workspace: git-basic-auth
        - name: output
          workspace: linked-workspace
      params:
        - name: url
          value: "$(params.REPO)"
        - name: revision
          value: main
    - name: build-and-push
      taskRef:
        name: buildah
      runAfter: [ 'fetch-repo' ]
      workspaces:
        - name: source
          workspace: linked-workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE_REF):$(params.IMAGE_TAG)"
        - name: CONTEXT
          value: ''
        - name: FORMAT
          value: docker
    - name: test-deploy
      taskRef:
        name: kubernetes-actions
      runAfter: [ 'build-and-push' ]
      params:
        - name: image
          value: public.ecr.aws/amazonlinux/amazonlinux:2.0.20221210.1-arm64v8
        - name: script
          value: |
            curl --silent --location -o /usr/local/bin/kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.7/2022-10-31/bin/linux/amd64/kubectl
            chmod +x /usr/local/bin/kubectl
            kubectl apply -f https://raw.githubusercontent.com/rajdurvasula/testnodedocker/main/manifest/deploy.yaml
      workspaces:
        - name: manifest-dir
          workspace: linked-workspace
        - name: kubeconfig-dir
          workspace: config-dir