---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nodeapp-pipeline-role
  namespace: rdapp
rules:
  - apiGroups: [ "extensions", "apps", "" ]
    resources: [ "services", "deployments", "pods", "pvc", "job" ]
    verbs: [ "get", "create", "update", "patch", "list", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodeapp-pipeline-role-bind
  namespace: rdapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nodeapp-pipeline-role
subjects:
  - kind: ServiceAccount
    name: docker-login
