---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnode-deploy
  namespace: rdapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testnode-app
  template:
    metadata:
      labels:
        app: testnode-app
    spec:
      containers:
        - name: testnode-app
          image: rajdurvasula/testnode-app:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testnode-svc
  namespace: rdapp
spec:
  type: LoadBalancer
  selector:
    app: testnode-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
